version: '3'
services: 
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    ports:
      - "3500:3500"
    environment:
      - PORT= 3500
      - NODE_ENV=production
    entrypoint: npm run start