version: '3'
services:
  nginx:
    ports:
      - "3000:80"

  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
#    ports:
#      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_USERNAME=root 
      - MONGO_PASS=root123
      - SESSION_SECRET=secret
    volumes:
      - ./:/app:ro
      - /app/node_modules

    