version: '3'
services:

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on: 
      - node-app 
  node-app:
    build: . 
    depends_on: 
      - mongo 

  mongo:
    image: mongo
    #ports:
    #  - "27017:27017"
    volumes:
      - mongodb:/data/db

    command: mongod --auth
  redis:
    image: redis:6.2.1

volumes:
  mongodb:





