version: '3'
services: 
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production

    # in production server, the enviroment variables will be taken form the machine enviroment vars
    environment:
      - PORT= 3000
      - NODE_ENV=production
      - MONGO_USERNAME=${MONGO_USERNAME} 
      - MONGO_PASS=${MONGO_PASS}
      - SESSION_SECRET=${SESSION_SECRET}

    entrypoint: npm run start
  
  mongo:
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}