version: '3'
services:
  node-app:
    build: . 
  
    networks:
      - net1
    depends_on: 
      - mongo 

  mongo:
    image: mongo
    environment:
        # provide your credentials here
        - MONGO_INITDB_ROOT_USERNAME=root 
        - MONGO_INITDB_ROOT_PASSWORD=root123
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
#      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - net1
    command: mongod --auth
volumes:
  mongodb:

networks:
  net1:




